export const CCD_DATA_API_CONFIG_REF = 'services.ccdDataApi'
export const COOKIE_TOKEN = 'cookies.token'
export const SECURE_COOKIE = 'secureCookie'
export const SESSION_SECRET = 'sessionSecret'
export const NOW = 'now'
export const APP_INSIGHTS_KEY = 'appInsightsInstrumentationKey'
export const MICROSERVICE = 'microservice'
export const LOGGING = 'logging'
export const PROXY_HOST = 'proxyConfig.host'
export const PROXY_PORT = 'proxyConfig.port'
export const COOKIES_USERID = 'cookies.userId'
export const MAX_LINES = 'exceptionOptions.maxLines'
export const IDAM_CLIENT = 'idamClient'
export const ENVIRONMENT = 'environment'
export const MAX_LOG_LINE = 'maxLogLine'
export const INDEX_URL = 'indexUrl'
export const OAUTH_CALLBACK_URL = 'oauthCallbackUrl'
export const PROTOCOL = 'protocol'

/**
 * Services
 */
export const SERVICE_S2S_PATH = 'services.s2s'
export const SERVICES_IDAM_API_PATH = 'services.idamApi'
export const SERVICES_IDAM_WEB = 'services.idamWeb'
export const SERVICES_RD_PROFESSIONAL_API_PATH = 'services.rdProfessionalApi'
export const SERVICES_CCD_DATA_API_PATH = 'services.ccdDataApi'
export const SERVICES_CCD_DEF_API_PATH = 'services.ccdDefApi'
