compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Note: intentionally leaving Angular Material/CDK older than core Angular.
# If peer dependency issues block install, consider using selectiveVersionResolutions
# or temporarily upgrading Material/CDK when feasible.
