nodejs:
  applicationPort: 3000
  memoryLimits: 1024Mi
  cpuLimits: 1000m
  environment:
    REFORM_TEAM: rpx
    REFORM_SERVICE_NAME: xui-ao-webapp
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    PUI_ENV: preview
    S2S_SECRET: ${S2S_SECRET}
    IDAM_SECRET: ${IDAM_SECRET}
    SESSION_SECRET: secretSauce
    NODE_TLS_REJECT_UNAUTHORIZED: 1
    PORT: 3000
    NOW: false
    IDAM_CLIENT: xuiaowebapp
    OAUTH_CALLBACK_URL: /oauth2/callback
    MAX_LOG_LINE: 80
    EXCEPTION_OPTIONS_MAX_LINES: 1
    INDEX_URL: /
    LOGGING: debug
    PROTOCOL: http
    SECURE_COOKIE: false
    COOKIE_TOKEN: __auth__
    COOKIE_USER_ID: __userid__
    MICROSERVICE: xui_webapp
    PROXY_HOST:
    PROXY_PORT: 0
  keyVaults:
    rpx:
      resourceGroup: rpx
      secrets:
        - xui-s2s-token
        - xui-oauth2-token
        - AppInsightsInstrumentationKey
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
