version: '2.1'

services:
#  dm-show:
#    image: hmcts/dm-show:latest
#    environment:
#    - NODE_ENV=development
#    - PORT=8080
#    - IDAM_LOGIN_URL=https://localhost:3501/login
#    - DM_STORE_APP_URI=http://dm-store:8080
#    - EM_ANNO_APP_URI=http://em-anno:8080
##    - EM_REDACT_APP_URI=http://em-redact:8080
#    - DM_UPLOAD_URL=/demproxy/dm/documents
#    - DM_OWNED_URL=/demproxy/dm/documents/owned
#    - DM_SEARCH_URL=/demproxy/dm/documents/filter
#    - IDAM_API_URI=http://idam-api:8080
#    - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
#    - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
#    - IDAM_SERVICE_NAME=em_gw
#    - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_WEBSHOW=AAAAAAAAAAAAAAAA
#    #      logging env vars
#    - ROOT_APPENDER=JSON_CONSOLE
#    - LOG_OUTPUT=single
#    - JSON_CONSOLE_PRETTY_PRINT=false
#    - REFORM_SERVICE_TYPE=node
#    - REFORM_SERVICE_NAME=dm-show
#    - REFORM_TEAM=evidence
#    - REFORM_ENVIRONMENT=docker
##      healthcheck env vars
#    - PACKAGES_ENVIRONMENT=docker
#    - PACKAGES_PROJECT=evidence
#    - PACKAGES_NAME=dm-show
#    - PACKAGES_VERSION=unkown
#    ports:
#     - 3608:8080

  dm-store:
    image: hmcts/dm-store:latest
    command: --wait-for-database 30
    environment:
      - SERVER_PORT=8080
      - IDAM_SUPERUSER_EMAIL
      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
      - GOV_NOTIFY_API_KEY
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dm-store-db:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - SPRING_PROFILES_ACTIVE=dev
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_API_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
      - http_proxy=
      - https_proxy=
      - no_proxy=
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=dm-store
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=dm-store
      - PACKAGES_VERSION=unkown
#      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
     - dm-store-db
     - idam-api
     - service-auth-provider-app
    depends_on:
     - dm-store-db
     - idam-api
     - service-auth-provider-app
    ports:
     - 4603:8080
#     - 5005:5005

  dm-store-db:
    image: hmcts/dm-store-db:latest
#    ports:
#     - 5432:5432
