ccd_data_api_service = "http://ccd-data-store-api-demo.service.core-compute-demo.internal"
ccd_definition_api_service = "http://ccd-definition-store-api-demo.service.core-compute-demo.internal"
idam_api_service = "https://idam-api.demo.platform.hmcts.net"
idam_web_service = "https://idam-web-public.demo.platform.hmcts.net"
rd_professional_api_service = "http://rd-professional-api-demo.service.core-compute-demo.internal"
s2s_service = "http://rpe-service-auth-provider-demo.service.core-compute-demo.internal"
fee_and_pay_api = "https://payment-api-demo.service.core-compute-demo.internal"
