#capacity = "2"
ccd_data_api_service = "http://ccd-data-store-api-demo.service.core-compute-demo.internal"
ccd_definition_api_service = "http://ccd-definition-store-api-demo.service.core-compute-demo.internal"
idam_api_service = "https://idam-api.ithc.platform.hmcts.net"
idam_web_service = "https://idam-web-public.ithc.platform.hmcts.net"
rd_professional_api_service = "http://rd-professional-ithc.service.core-compute-ithc.internal"
s2s_service = "http://rpe-service-auth-provider-ithc.service.core-compute-ithc.internal"
