#capacity = "2"
ccd_data_api_service = "http://ccd-data-store-api-ithc.service.core-compute-ithc.internal"
ccd_definition_api_service = "http://ccd-definition-store-api-ithc.service.core-compute-ithc.internal"
idam_api_service = http://idam-api-ithc.service.core-compute-ithc.internal"
idam_web_service = "https://idam-web-public-aks.ithc.platform.hmcts.net"
rd_professional_api_service = "http://rd-professional-api-ithc.service.core-compute-ithc.internal"
s2s_service = "http://rpe-service-auth-provider-ithc.service.core-compute-ithc.internal"
fee_and_pay_api = "https://payment-api-ithc.service.core-compute-ithc.internal"
