ccd_data_api_service = "https://ccd-data-store-api-demo.service.core-compute-demo.internal"
ccd_definition_api_service = "https://ccd-definition-store-api-demo.service.core-compute-demo.internal"
idam_api_service = "https://idam-api.perftest.platform.hmcts.net"
idam_web_service = "https://idam-web-public.perftest.platform.hmcts.net"
rd_professional_api_service = "https://rd-professional-api-perftest.service.core-compute-perftest.internal"
s2s_service = "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
