additional_host_name = "administer-orgs.platform.hmcts.net"

ccd_data_api_service = "http://ccd-data-store-api-demo.service.core-compute-demo.internal"
ccd_definition_api_service = "http://ccd-definition-store-api-demo.service.core-compute-demo.internal"
idam_api_service = "https://idam-api.platform.hmcts.net"
idam_web_service = "https://hmcts-access.service.gov.uk"
rd_professional_api_service = "http://rd-professional-api-prod.service.core-compute-prod.internal"
s2s_service = "http://rpe-service-auth-provider-prod.service.core-compute-prod.internal"
iss_service = "https://forgerock-am.service.core-compute-idam-prod.internal:8443/openam/oauth2/hmcts"
fee_and_pay_api = "http://payment-api-prod.service.core-compute-prod.internal"
