version: '2.1'

services:

  em-anno:
    image: hmcts/em-anno:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_API_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
      - SPRING_DATASOURCE_URL=jdbc:postgresql://em-anno-db:5432/annotation
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=em-anno
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=em-anno
      - PACKAGES_VERSION=unkown
#      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
     - em-anno-db
     - idam-api
     - service-auth-provider-app
    depends_on:
     - em-anno-db
     - idam-api
     - service-auth-provider-app
    ports:
      - 4621:8080
#     - 5005:5005

  em-anno-db:
    image: hmcts/em-anno-db:latest
#    ports:
#      - 5432:5432

  em-redact:
    image: hmcts/em-redact:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_API_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-app:8489
      - SPRING_DATASOURCE_URL=jdbc:postgresql://em-redact-db:5432/redaction
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=em-redact
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=em-anno
      - PACKAGES_VERSION=unkown
#      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
     - em-redact-db
     - idam-api
     - service-auth-provider-app
    depends_on:
     - em-redact-db
     - idam-api
     - service-auth-provider-app
#    ports:
#      - 4623:8080

  em-redact-db:
    image: hmcts/em-redact-db:latest
#    ports:
#      - 5432:5432
